---
- name: Kubernetes Apps | Wait for kube-apiserver
  uri:
    url: "{{ kube_apiserver_endpoint }}/healthz"
    validate_certs: no
    client_cert: "{{ kube_apiserver_client_cert }}"
    client_key: "{{ kube_apiserver_client_key }}"
  register: result
  until: result.status == 200
  retries: 20
  delay: 1
  when: inventory_hostname == groups['kube_control_plane'][0]

- name: Kubernetes Apps | DNS
  vars:
    ansible_python_interpreter: "{{ kubespray_virtualenvs_base }}/kubernetes.core/bin/python"
  kubernetes.core.k8s:
    state: present
    apply: true
    server_side_apply:
      field_manager: kubespray
      force_conflicts: true
    template: "{{ all_manifests_lists | flatten }}"
  register: result
  until: result is succeeded
  retries: 10
  delay: 5
  tags:
    - coredns
    - nodelocaldns

- name: Kubernetes Apps | Etcd metrics endpoints
  import_tasks: etcd_metrics.yml
  when: etcd_metrics_port is defined and etcd_metrics_service_labels is defined
  tags:
    - etcd_metrics

- name: Kubernetes Apps | Netchecker
  import_tasks: netchecker.yml
  when: deploy_netchecker
  tags:
    - netchecker

- name: Kubernetes Apps | Dashboard
  import_tasks: dashboard.yml
  when: dashboard_enabled
  tags:
    - dashboard
