---
- name: Set kubelet api version to v1beta1
  set_fact:
    kubeletConfig_api_version: v1beta1
  tags:
    - kubelet
    - kubeadm

- name: Write kubelet environment config file (kubeadm)
  template:
    src: "kubelet.env.{{ kubeletConfig_api_version }}.j2"
    dest: "{{ kube_config_dir }}/kubelet.env"
    setype: "{{ (preinstall_selinux_state != 'disabled') | ternary('etc_t', omit) }}"
    backup: yes
    mode: 0600
  notify: Node | restart kubelet
  tags:
    - kubelet
    - kubeadm

- name: Gather facts about the node
  setup:
    filter: ansible_memtotal_mb,ansible_processor_vcpus
  tags:
    - kubelet
    - kubeadm

- name: Check if kube_enable_auto_reserved_resources is set
  set_fact:
    kube_master_cpu_reserved: "{{ (ansible_processor_vcpus * 1000 * 0.01) | int + 80 }}m"
    kube_master_memory_reserved: "{{ (ansible_memtotal_mb * 0.05) | int + 330 }}Mi"
  tags:
    - kubelet
    - kubeadm
  when:
    - kube_enable_auto_reserved_resources
    - is_kube_master

- name: Check if kube_enable_auto_reserved_resources is set
  set_fact:
    kube_cpu_reserved: "{{ (ansible_processor_vcpus * 1000 * 0.01) | int + 80 }}m"
    kube_memory_reserved: "{{ (ansible_memtotal_mb * 0.05) | int + 330 }}Mi"
  tags:
    - kubelet
    - kubeadm
  when:
    - kube_enable_auto_reserved_resources
    - not is_kube_master

- name: Write kubelet config file
  template:
    src: "kubelet-config.{{ kubeletConfig_api_version }}.yaml.j2"
    dest: "{{ kube_config_dir }}/kubelet-config.yaml"
    mode: 0600
  notify: Kubelet | restart kubelet
  tags:
    - kubelet
    - kubeadm

- name: Write kubelet systemd init file
  template:
    src: "kubelet.service.j2"
    dest: "/etc/systemd/system/kubelet.service"
    backup: "yes"
    mode: 0600
    validate: "sh -c '[ -f /usr/bin/systemd/system/factory-reset.target ] || exit 0 && systemd-analyze verify %s:kubelet.service'"
    # FIXME: check that systemd version >= 250 (factory-reset.target was introduced in that release)
    # Remove once we drop support for systemd < 250
  notify: Node | restart kubelet
  tags:
    - kubelet
    - kubeadm

- name: Flush_handlers and reload-systemd
  meta: flush_handlers

- name: Enable kubelet
  service:
    name: kubelet
    enabled: yes
    state: started
  tags:
    - kubelet
  notify: Kubelet | restart kubelet
