---
scheduler_plugins_enabled: false

# second_scheduler or single_scheduler. See https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/install.md#install-release-v0278-and-use-coscheduling
scheduler_plugins_single_scheduler_mode: true

scheduler_plugins_namespace: scheduler-plugins

scheduler_plugins_scheduler_name: scheduler-plugins-scheduler

scheduler_plugins_controller_replicas: 1

scheduler_plugins_scheduler_replicas: 1

# The default is determined by the number of control plane nodes.
scheduler_plugins_scheduler_leader_elect: "{{ ((groups['kube_control_plane'] | length) > 1) }}"

# Plugins to enable. See https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/manifests/install/charts/as-a-second-scheduler/README.md#configuration for more info.
scheduler_plugins_enabled_plugins:
  - Coscheduling
  - CapacityScheduling
  - NodeResourceTopologyMatch
  - NodeResourcesAllocatable

# Plugins to disable. See https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/manifests/install/charts/as-a-second-scheduler/README.md#configuration for more info.
scheduler_plugins_disabled_plugins:
  - PrioritySort

# Customize the enabled plugins' config.
# Refer to the "pluginConfig" section of https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/manifests/<plugin>/scheduler-config.yaml.
scheduler_plugins_plugin_config:
  - name: Coscheduling
    args:
      permitWaitingTimeSeconds: 10      # default is 60

# List of scheduler extenders (dicts), each holding the values of how to communicate with the extender.
scheduler_plugins_scheduler_extenders: []
